CREATE TABLE public.reviews (
	review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	review_firstname character varying NOT NULL,
	review_lastname character varying NOT NULL,
	review_rating integer NOT NULL,
	review_comment character varying NOT NULL,
	inventory_id integer NOT NULL,
	CONSTRAINT review_pk PRIMARY KEY (review_id)
);

INSERT INTO public.reviews (
    review_firstname,
    review_lastname,
    review_rating,
    review_comment,
    inventory_id
  )
VALUES   (
    'Michaela',
    'Test',
    5,
    'This car has been great for us! WE love it so much',
    1
  ), (
    'Liam',
    'Test',
    4,
    'This car is almost perfect. Mileage is not great',
    2
  ), (
    'Cher',
    'Van',
    5,
    'Love this car, great family vehicle',
    3
  ), (
    'Carl',
    'Cruz',
    2,
    'The car is not as good as I thought it would be. Kind of disappointed',
    4
  ), (
    'Jerry',
    'Lane',
    1,
    'If I could give this car -100 I would.',
    5
  ), (
    'Carrie',
    'Love',
    28,
    'Love this plane, so worth it',
    6
  ), (
    'Arnold',
    'Harris',
    4,
    'Love the car, cant recommend CSE motors enough.',
    7
  ), (
    'Harry',
    'Potter',
    3,
    'Good mileage, AC does not work so well though.',
    8
  ), (
    'Callie',
    'Smith',
    1,
    'Hard a really hard time getting used to this car.',
    9
  ), (
    'Gabby',
    'Lowis',
    4,
    'Love this car so much. Great company too!',
    10
  ), (
    'Rush',
    'Cash',
    2,
    'Not a great car. Transmission went out way too quickly.',
    11
  ), (
    'Henry',
    'Ford',
    5,
    'Everyone should drive one of these.',
    12
  ), (
    'Scooby',
    'Doo',
    5,
    'Excellent van. We couldnt do our job without it!',
    13
  ),
  (
    'Kylie',
    'Lenton',
    1,
    'Do not buy this car!',
    14
  ),
  (
    'Randy',
    'Grain',
    4,
    'Amazing car, so great for the fam.',
    25
  ), 
    (
    'Michaela',
    'Keel',
    4,
    'Amazing car. Great for the price.',
    26
  ), 
    (
    'Phoebe',
    'Sith',
    2,
    'Would not bug again',
    29
  ), 
    (
    'Sophie',
    'Wendal',
    4,
    'Would bug again',
    31
  ), 
    (
    'Tempe',
    'Booth',
    3,
    'Car is ok to drive.',
    31
  ), 
  (
    'Vicky',
    'Angel',
    5,
    'After searching for months we finally found this car! Worth the wait.',
    15
  );